# Generated by Django 5.1.1 on 2024-11-07 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='наименование категории')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование заметки')),
                ('description', models.CharField(max_length=255, verbose_name='Ваше описание')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='дедлайн')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('orange', 'Оранжевый'), ('green', 'Зеленый')], default='green', max_length=10, verbose_name='цвет заметки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='todo_list.categories')),
            ],
        ),
    ]
