# Generated by Django 5.1.1 on 2024-10-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_categories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='categories',
            new_name='category',
        ),
    ]
