# Generated by Django 5.1.1 on 2024-10-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_rename_categories_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=16, verbose_name='наименование категории'),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.categories'),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(max_length=25, verbose_name='цвет заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, verbose_name='наименование заметки'),
        ),
    ]
