# Generated by Django 5.1.1 on 2024-10-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_categories_name_alter_note_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='todo_list.categories'),
        ),
    ]
