# Generated by Django 5.1.1 on 2024-10-28 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_alter_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='наименование категории'),
        ),
    ]
