# Generated by Django 5.1.1 on 2024-10-29 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дедлайн'),
        ),
        migrations.AddField(
            model_name='note',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='наименование категории'),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('red', 'Красный'), ('orange', 'Оранжевый'), ('green', 'Зеленый')], default='green', max_length=10, verbose_name='цвет заметки'),
        ),
    ]
