# Generated by Django 5.1.1 on 2024-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_note_deadline_note_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
    ]
